### ISSUE TITLE
Impossible to install the addon on Firefox

### ISSUE THREAD

**Issue by Synochy** [e-alfred/ocDownloader_palemoon#1]
I tried to install this addon with firefox catalog and with the file and neither of them worked:
- with the catalog, I have this message: "We couldn't download this addon because of a failure of connexion". My internet is working fine so I don't think it is a problem on my computer
- with the file, I have this message: "We can't install this addon because we couldn't verify it"

Do you have any idea about what is the problem ?

**Comment by e-alfred** [comment]
This sounds strange. Did you try to install another extension from AMO and does that work? Which Firefox version do you use?

For the file itself, which one did you use? From AMO? Firefox requires a signed extension for installation, aside from that it would only be possible to use it as a temporary extension for debugging. 

Additionally, the extension in this repository uses old technology that won't be supported from Firefox 57 onwards. A compatible extension can be found here: https://github.com/e-alfred/ocDownloader_ChromeExtension

I tried to install it on Firefox 56 through the addons menu and it installs without a problem.

**Comment by e-alfred** [comment]
I will close this for now. Please reopen if you have any further problems. Newer Firefox releases only work with Webextensions anymore anyway.
